Testing some Future corner cases
Rust can call the waker callback after the future is completed, which
our foreign bindings code doesn't handle well.

The simplest way for this to happen is when you race 2 futures.  The
future resolves when the first future is complete, causing the foreign
bindings to destroy the waker callback.  When the second future
completes, Rust still calls the foreign waker callback, which should
just be a no-op.  However, the foreign waker tries to poll the Rust
after it's already completed which fails.

Here's the debugging output of the TestFutures.test_race_say_after test
which shows this in action:

```
RustFutureForeignWaker -- poll 0x7f3d38444010 0x0 (SystemTime { tv_sec: 1680536419, tv_nsec: 638164003 })
RustFutureForeignWaker -- clone (SystemTime { tv_sec: 1680536419, tv_nsec: 638292008 })
RustFutureForeignWaker -- clone (SystemTime { tv_sec: 1680536419, tv_nsec: 638379958 })
RustFutureForeignWaker -- Poll::Pending
RustFutureForeignWaker -- drop (SystemTime { tv_sec: 1680536419, tv_nsec: 638521745 })
RustFutureForeignWaker -- wake (SystemTime { tv_sec: 1680536420, tv_nsec: 138447039 })
RustFutureForeignWaker -- poll 0x7f3d38444010 0x0 (SystemTime { tv_sec: 1680536420, tv_nsec: 138616654 })
RustFutureForeignWaker -- Poll::Ready
RustFutureForeignWaker -- drop (SystemTime { tv_sec: 1680536420, tv_nsec: 138675772 })
RustFutureForeignWaker -- wake (SystemTime { tv_sec: 1680536420, tv_nsec: 638494180 })
RustFutureForeignWaker -- poll 0x7f3d38444010 0x0 (SystemTime { tv_sec: 1680536420, tv_nsec: 638662016 })
test uniffi_foreign_language_testcase_test_futures_py ... FAILED

failures:

---- uniffi_foreign_language_testcase_test_futures_py stdout ----
Error: running `python3` failed
```

This case could be fixed by having the waker track if the future is
completed and not poll after that.  However, I believe there's a worse
case that we can't easily work around: if the async function finishes,
then the foreign code should destroy the waker callback and drop the
Rust future.  Then when the second future completes, it will try to call
the waker function which is now a dangling pointer and we crash.

I updated the swift tests to trigger this.

I wasn't able to trigger that on Python because there's a tangle of
references between `trampoline`, `Future`, `waker`, and the
`FUTURE_WAKER_T` wrapper that prevents anything from being GCed. It's
possible that Python avoids the issue because it's leaking waker
callbacks and never destroying them.  It's also possible that python
will eventually figure out the reference cycle, destroy the callback,
which and any future waker callback invocations will crash.

I made a second test that Python cleans up the future once it's
completed.  Once this test passes, then I think we should be able to
trigger the second form of the wake-after-complete bug.